---
language: ruby
env:
  global:
    - "RACK_ENV=test"
rvm:
  - 2.1.1
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script:
  - bundle exec rake
  - RACK_ENV=test bundle exec rake konacha:run
